repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=4000']
      - id: debug-statements
      - id: detect-private-key

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: ['--line-length=88']
        exclude: ^docs/|.*\.(json|yaml|md|txt)$

  # Add local hooks to run custom commands
  - repo: local
    hooks:
      - id: run-make-format
        name: Run Make Format
        entry: make format
        language: system
        pass_filenames: false
  # - repo: https://github.com/pycqa/flake8
  #   rev: 4.0.1
  #   hooks:
  #     - id: flake8
  #       args: ['--max-line-length=88']
