blank_issues_enabled: false
contact_links:
  - name: ğŸ‘ Upvote an issue
    url: https://github.com/SylphAI-Inc/AdalFlow/issues
    about: You should upvote an issue if it is important to you.
  - name: ğŸ’¬ Chat with us
    url: https://discord.gg/ezzszrRZvT
    about: Live chat with experts, engineers, and users in our Discord community.
  - name: ğŸ“– Read the documentation
    url: http://adalflow.sylph.ai/
    about: Please consult the documentation before opening any issues!
  # - name: ğŸ™‹ Contact us about professional services
  #   url: https://lightning.ai
  #   about: Contact the Lightning.ai sales team for paid support.
